baseURL = "https://blog.manuel-reinhardt.com/"
languageCode = "en-us"
title = "manuel-rhdt's thoughts"

theme = "vienna"
themesDir = "themes"

DefaultContentLanguage = "en"

[params]
author = "Manuel Reinhardt"
bio = "I'm a physics student and programmer based in Munich, Germany. My current interests include Rust, Static Site Generators and Font rasterization."
avatar = "/images/profile-pic.jpg"
image = ""
